# cargo-deny configuration for TaskHub
# See: https://embarkstudios.github.io/cargo-deny/

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
    # Add specific advisory IDs to ignore if needed
    # "RUSTSEC-0000-0000",
    "RUSTSEC-2024-0436",
]

[licenses]
# License policy for dependencies
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = [
    # Add specific crates with non-standard licenses if needed
]

[licenses.private]
# Ignore dev dependencies for license checking
ignore = true
registries = []

[bans]
# Banned crates and features
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
# Source repository restrictions
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
