name: security
on: [pull_request, push, workflow_dispatch]

jobs:
  scan:
    name: leak-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    #   - uses: gitleaks/gitleaks-action@v2
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Additional secret scanning with TruffleHog
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified 